# Generated by Django 4.2.4 on 2023-08-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(verbose_name='Beginning Date')),
                ('end_date', models.DateField(verbose_name='Ending Date')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UntimedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('text', models.TextField(verbose_name='Notes')),
                ('domains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannerFinal.domain')),
            ],
        ),
        migrations.CreateModel(
            name='TimedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('start_date_time', models.DateTimeField(verbose_name='Entry Date')),
                ('end_date_time', models.DateTimeField(verbose_name='Due Date')),
                ('text', models.TextField(verbose_name='Description')),
                ('complete', models.BooleanField()),
                ('domains', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plannerFinal.domain')),
            ],
        ),
    ]
