# Generated by Django 4.2.4 on 2023-09-01 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plannerFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timedentity',
            name='domains',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timedEntity', to='plannerFinal.domain'),
        ),
        migrations.AlterField(
            model_name='untimedentity',
            name='domains',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='untimedEntity', to='plannerFinal.domain'),
        ),
    ]
